import { Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sensi-AI Carer Coach",
  description: "Generated by Atharva",
};

export default function RootLayout({ children }) {
  return (
      <ClerkProvider 
      appearance={{
        baseTheme: dark,
      }}
      >

    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${inter.clas}`}>
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            >
            <Header/>
            <main className="min-h-screen">{children}</main>
            <Toaster richColors />
            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4  text-center text-gray-200">
                <p>love from me </p>
              </div>
            </footer>
          </ThemeProvider>
      </body>
    </html>
    
            </ClerkProvider>
  );
}
